# Generated by Django 5.0.7 on 2024-07-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sunday', models.BooleanField(default=False)),
                ('festivita', models.BooleanField(default=False)),
                ('ferie', models.BooleanField(default=False)),
                ('recupero', models.BooleanField(default=False)),
                ('daily_pay', models.DecimalField(decimal_places=2, default=420, max_digits=10)),
                ('day', models.DateField()),
            ],
        ),
    ]
