# Generated by Django 5.0.7 on 2024-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='daily_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
