# Generated by Django 5.0.7 on 2024-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_alter_salary_daily_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
