# Generated by Django 5.0.7 on 2024-07-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0004_salary_base_end_time_salary_base_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['day']},
        ),
    ]
