# Generated by Django 5.0.7 on 2024-07-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0005_alter_salary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='base_end_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='extra_end_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='extra_start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
