# Generated by Django 5.0.7 on 2024-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0007_alter_salary_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
